# Generated by Django 5.2.2 on 2025-06-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deltabroker',
            name='password',
            field=models.CharField(blank=True, max_length=16, null=True),
        ),
    ]
