# Generated by Django 5.2.2 on 2025-06-06 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0002_alter_deltabroker_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='deltabroker',
            name='otp_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='deltabroker',
            name='otp_verified',
            field=models.BooleanField(default=False),
        ),
    ]
