# Generated by Django 5.2.2 on 2025-06-06 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0004_apilog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apilog',
            options={'ordering': ['-datetime']},
        ),
        migrations.AlterModelTable(
            name='apilog',
            table='api_logs',
        ),
    ]
