# Generated by Django 5.2.2 on 2025-06-07 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0005_alter_apilog_options_alter_apilog_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='apilog',
            name='error',
        ),
        migrations.RemoveField(
            model_name='apilog',
            name='user',
        ),
        migrations.AlterField(
            model_name='apilog',
            name='message',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
