# Generated by Django 5.2.2 on 2025-06-17 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0006_remove_apilog_error_remove_apilog_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.BigIntegerField(blank=True, null=True)),
                ('product_id', models.IntegerField(blank=True, null=True)),
                ('client_order_id', models.CharField(blank=True, max_length=24, null=True)),
                ('symbol', models.CharField(blank=True, max_length=10, null=True)),
                ('side', models.CharField(blank=True, max_length=10, null=True)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('order_type', models.CharField(blank=True, max_length=50, null=True)),
                ('limit_price', models.CharField(blank=True, max_length=50, null=True)),
                ('time_in_force', models.CharField(blank=True, max_length=50, null=True)),
                ('post_only', models.CharField(blank=True, max_length=50, null=True)),
                ('reduce_only', models.CharField(blank=True, max_length=50, null=True)),
                ('order_status', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, db_column='email', null=True, on_delete=django.db.models.deletion.SET_NULL, to='brokers.deltabroker', to_field='email')),
            ],
            options={
                'db_table': 'orders',
                'ordering': ['-created_at'],
            },
        ),
    ]
