# Generated by Django 5.2.2 on 2025-06-17 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokers', '0007_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='deltabroker',
            name='set_password',
            field=models.BooleanField(default=False),
        ),
    ]
